apiVersion: v1
kind: Service
metadata:
  name: flume
  labels:
    name: flume
    app: flume
spec:
  ports:
  - port: 9999
    name: flume
    targetPort: 9999
  selector:
    name: flume
    app: flume
