apiVersion: "v1"
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
    app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - name: mongo
          containerPort: 27017
          protocol: TCP 
