apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongoclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: slow
  selector:
    matchLabels:
      type: NFS
