apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    name: nodeapp
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: astro3/nodeapp
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
          name: nodeapp
          protocol: TCP
