apiVersion: v1
kind: Service
metadata:
   name: nodeapp
   labels:
     name: nodeapp
     app: nodeapp
spec:
  selector:
    name: nodeapp
  type: NodePort
  ports:
  - port: 3000
    name: nodeapp
    targetPort: 3000
    protocol: TCP
