apiVersion: "v1"
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - name: http
          containerPort: 6379
          protocol: TCP
